In [305]:
import numpy as np


In [306]:
Xi = 2

max_size = 2

Intervals = np.ceil(Xi/max_size)

In [307]:
X,Y = np.meshgrid(np.arange(-Xi,Xi+1), np.arange(-Xi,Xi+1))

print(len(np.ravel(X)))
print(X)

25
[[-2 -1  0  1  2]
 [-2 -1  0  1  2]
 [-2 -1  0  1  2]
 [-2 -1  0  1  2]
 [-2 -1  0  1  2]]


In [308]:
#name the variable below aptly

segments = np.arange(-Intervals, Intervals)*max_size #Xi appears at positive end

anomalous_interval = Xi + segments[1]
print(anomalous_interval)


A, B  = np.meshgrid(segments,segments)

print(A)


2.0
[[-2.  0.]
 [-2.  0.]]


In [309]:
count = 0
for i in range(len(A)):
    for j in range(len(A)):

        ##santise the ranges

        if A[i,j] < -Xi:
            a_from = -Xi
            a_to = -Xi + anomalous_interval
        elif A[i,j] + max_size> Xi:
            a_from = A[i,j]
            a_to = Xi
        else:
            a_from = A[i,j]
            a_to = A[i,j] + max_size
        
        #same for b
        if B[i,j] < -Xi:
            b_from = -Xi
            b_to = -Xi + anomalous_interval
        elif B[i,j] + max_size> Xi:
            b_from = B[i,j]
            b_to = Xi
        else:
            b_from = B[i,j]
            b_to = B[i,j] + max_size




        a1 = np.arange(a_from, a_to)
        b1 = np.arange(b_from, b_to)
        A1, B1 = np.meshgrid(a1,b1)

        count += len(np.ravel(A1))

    
    print('\n \n')

print(count)


 


 

16


In [310]:
print(A.ravel())

[-2.  0. -2.  0.]


In [311]:

#print in scientitfic notation
print('{:.2e}'.format((1e4)**(3/2)))


1.00e+06


In [312]:
bounds = np.array([-10,3,4])
print(bounds+1)

[-9  4  5]


In [313]:
np.min([bounds**2,(bounds+1)**2], axis=0)


if np.sum(np.min([bounds**2,(bounds+1)**2], axis=0)) > cutoff:
    

IndentationError: expected an indented block (954584194.py, line 5)

In [314]:
a = np.array([2,2,2])




X,Y = np.meshgrid(a,a)

#X, Y = np.ravel(X), np.ravel(Y)


print(X)




[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [315]:
coords = np.vstack([X.ravel(), Y.ravel(), Z.ravel()])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 9 and the array at index 2 has size 8365427

In [316]:
np.einsum('ij,ij->i', coords, coords)

ValueError: operand has more dimensions than subscripts given in einstein sum, but no '...' ellipsis provided to broadcast the extra dimensions.

In [317]:
def method1():
    Xi = 200
    x,y,z = np.meshgrid(np.arange(-Xi,Xi+1), np.arange(-Xi,Xi+1), np.arange(-Xi,Xi+1))
    r = np.vstack([x.ravel(), y.ravel(), z.ravel()])
    r_2 = np.einsum('ij,ij->i', r, r)

    return r_2[r_2<100]

def method2():
    Xi = 200
    x,y,z = np.mgrid[-Xi:Xi+1, -Xi:Xi+1, -Xi:Xi+1]
    r_2 = x**2 + y**2 + z**2

    return r_2[r_2<100]


def method3():
    Xi = 200
    x,y,z = np.meshgrid(np.arange(-Xi,Xi+1), np.arange(-Xi,Xi+1), np.arange(-Xi,Xi+1))
    r = np.vstack([x, y, z])
    r_2 = np.einsum('ij,ij->i', r, r)

    return r_2[r_2<100]

In [318]:
%timeit method1()

2.06 s ± 46.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [319]:
%timeit method2()

2.31 s ± 168 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [320]:
%timeit method3()

ValueError: operand has more dimensions than subscripts given in einstein sum, but no '...' ellipsis provided to broadcast the extra dimensions.

In [ ]:
%timeit np.ndindex(3,3)

9.17 µs ± 70.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [ ]:
np.log(10)

2.302585092994046

# Direct Comparison

In [ ]:
import numpy as np
from tqdm import tqdm

In [ ]:
cutoff = 1e4

In [ ]:


Xi = int(np.sqrt(cutoff))+1 #+1 to make sure xi^2 is in range
    
max_size = 50
partitions = int(np.ceil(Xi/max_size))
intervals = np.arange(-partitions, partitions)*max_size #Xi appears at positive end
#does not change the result

A, B, C  = np.meshgrid(intervals,intervals, intervals) 

r_2_list = np.array([], dtype=np.int64)
sum_r_2 = 0

result = 0
for i in tqdm(range(len(A))):
    for j in range(len(A[i])):
        for k in range(len(A[i,j])):
                    lower_bounds = np.array([A[i,j,k],B[i,j,k],C[i,j,k]])
                    upper_bounds = lower_bounds + max_size

                    #if the minima (of magnitudes) are all below the cutoff, proceed
                    if np.sum(np.min([lower_bounds**2,upper_bounds**2], axis=0)) <=cutoff:



                            x1 = np.arange(lower_bounds[0], upper_bounds[0]) 
                            y1 = np.arange(lower_bounds[1], upper_bounds[1])
                            z1 = np.arange(lower_bounds[2], upper_bounds[2])


                            X,Y,Z = np.meshgrid(x1,y1,z1)


                            r = np.stack([X.ravel(), Y.ravel(), Z.ravel()], axis=1)


                            r_2 = np.einsum("ij,ij->i", r,r)


                            r = r[r_2<=cutoff]

                            r_2 = r_2[r_2<=cutoff]

                            r_2_list = np.append(r_2_list, r_2)

                            sum_r_2 += np.sum(r_2)






r_2_list = np.sort(r_2_list)
print(r_2_list)
a = 1/(r_2_list-0.5)

res1 = np.sum(a)
print(np.sum(a))

100%|██████████| 6/6 [00:00<00:00, 11.10it/s]

[    0     1     1 ... 10000 10000 10000]
1257.5870842526792


In [ ]:
rng = np.arange(-int(np.sqrt(cutoff))-1, int(np.sqrt(cutoff))+2)
res = (rng[:,np.newaxis, np.newaxis]**2+rng[np.newaxis,:,np.newaxis]**2+rng[np.newaxis,np.newaxis,:]**2)
X,Y,Z = np.meshgrid(rng,rng,rng, indexing = 'ij')
coords = np.stack((X,Y,Z), axis=3)
r = coords[res<=cutoff]

####### parallel and perp components of r
r_2 = np.einsum("ij,ij->i", r,r)


print(sum(r_2))
print(np.sort(r_2))




#r_2 = np.sort(r_2)
a = 1/(r_2-0.5)

res2 = np.sum(a)
print(np.sum(a))


25123412820
[    0     1     1 ... 10000 10000 10000]
1257.5870842526788


In [164]:
print(res1-res2)

4.547473508864641e-13


## Explanation of Discrepancy between new (large) method and old zeta

The reason for this is that recurring binary numbers (eg 0.1) are clipped when the memory allocated to the variable runs out. So 
$ \frac 1 a + \frac 1 b + \frac 1 c \neq \frac 1 b + \frac 1 c + \frac 1 a$.

This error is small depending on the number used, so we just have to ignore the final zeros. This explains the difference between the numbers,
it is this numerical instability, the grouping of values for zeta large reshuffels them when adding the reciprocals.

In [162]:
1/2**52

2.220446049250313e-16

In [502]:
x = 0.0125

In [503]:

terms1 = np.exp(-0.1*(r_2_list-x))/(r_2_list-x)
k1 = np.round(terms1,5)

print(r_2_list)
print(min(terms1))

[    0     1     1 ... 10000 10000 10000]
-80.10006252604981


In [504]:
np.exp(0.1*1e-4)/(-1e-4)

-10000.1000005

In [505]:
terms2 = np.exp(-0.1*(r_2-x))/(r_2-x)

k2 = np.round(terms2,8)


In [506]:
print(k1-k2)

[-80.10006   0.91744   0.91744 ...   0.        0.        0.     ]


In [507]:
2**(-53)*len(r_2_list)

4.649455265237634e-10

In [497]:
print(np.sum(k1))

34.545399999999994


In [498]:
print(terms1)

[-2.10254219  1.90245885  1.90245885 ...  0.          0.
  0.        ]


In [508]:


num_samples = 10
bootstrap = np.array([])
temp = np.copy(terms1)

for _ in range(num_samples):
    np.random.shuffle(temp)
    sample = sum(temp)
    bootstrap = np.append(bootstrap, sample)


error_estimate = np.std(bootstrap)
print("Error estimate:", error_estimate)




Error estimate: 1.0095559622109881e-12


In [509]:
a, b = np.unique(terms1, return_counts=True)



#print fully precision of a[0] in binary

print('{:.52f}'.format(a[0]))

len(bin(1000)[2:])





print('{:.52f}'.format(2**(-42)))

-80.1000625260498111401830101385712623596191406250000000
0.0000000000002273736754432320594787597656250000000000


In [510]:
np.finfo(np.float64)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

In [515]:
#squaresum of terms1
np.sqrt(np.sum(terms1**2))*1e-15




8.015319192820261e-14

In [514]:
print(abs(np.sum(terms1))*1e-15)

5.353248465640082e-14


In [386]:
2**(-52)

2.220446049250313e-16

In [517]:
np.log(4/3)/np.log(10)*2/3

0.08329249107219994

We generally need a way to find maximum values in a sum! Once we know the maximum value we can easily approximate the numerical error!

# A further note generally on precision. 

The amount of error strongly depends on the location of the lattice points wrt to the asymptotes. if we have the worst case scenario the for the sum

$\frac{1}{r^2-x}\; x = 2^{-53}$ which is the precision of storing. In that case the term (obviously) equals $2^{52}$ and the final comma space equals to the 2^0, i.e. one. This means if we include these precisions, then clipping could lead to an error of up to 1. Hence we should regularize all input numbers to some specified precision (and output as well).

In [282]:
2**(-26)

1.4901161193847656e-08

In [283]:
1/_*2**-52

1.4901161193847656e-08

So a precision of 2**(-26) seems to be ideal, and this is the number everything should be rounded to.

In [288]:
print(np.round(sum(k1) - sum(k2),8))

0.0


In [290]:
1/np.log(10)

0.43429448190325176

In [291]:
np.exp(-100)

3.720075976020836e-44

In [292]:
np.log(np.pi)/np.log(10)

0.4971498726941338

In [293]:
alpha = 0.01
Xi = 1e4

print(1/alpha-Xi*np.sqrt(np.pi/alpha))

-177145.3850905516


In [485]:


print('{:.52f}'.format(0.1))

0.1000000000000000055511151231257827021181583404541016


In [ ]:
print('{:.52f}'.format(0.1))