In [1]:
import numpy as np


In [108]:
Xi = 4

max_size = 2

Intervals = np.ceil(Xi/max_size)

In [109]:
X,Y = np.meshgrid(np.arange(-Xi,Xi), np.arange(-Xi,Xi))

print(len(np.ravel(X)))
print(X)

64
[[-4 -3 -2 -1  0  1  2  3]
 [-4 -3 -2 -1  0  1  2  3]
 [-4 -3 -2 -1  0  1  2  3]
 [-4 -3 -2 -1  0  1  2  3]
 [-4 -3 -2 -1  0  1  2  3]
 [-4 -3 -2 -1  0  1  2  3]
 [-4 -3 -2 -1  0  1  2  3]
 [-4 -3 -2 -1  0  1  2  3]]


In [110]:
a = np.arange(-Intervals, Intervals)*max_size #Xi appears at positive end

anomalous_interval = Xi + a[1]
print(anomalous_interval)


A, B  = np.meshgrid(a,a)

print(A)


2.0
[[-4. -2.  0.  2.]
 [-4. -2.  0.  2.]
 [-4. -2.  0.  2.]
 [-4. -2.  0.  2.]]


In [113]:
count = 0
for i in range(len(A)):
    for j in range(len(A)):

        ##santise the ranges

        if A[i,j] < -Xi:
            a_from = -Xi
            a_to = -Xi + anomalous_interval
        elif A[i,j] + max_size> Xi:
            a_from = A[i,j]
            a_to = Xi
        else:
            a_from = A[i,j]
            a_to = A[i,j] + max_size
        
        #same for b
        if B[i,j] < -Xi:
            b_from = -Xi
            b_to = -Xi + anomalous_interval
        elif B[i,j] + max_size> Xi:
            b_from = B[i,j]
            b_to = Xi
        else:
            b_from = B[i,j]
            b_to = B[i,j] + max_size




        a1 = np.arange(a_from, a_to)
        b1 = np.arange(b_from, b_to)
        A1, B1 = np.meshgrid(a1,b1)

        count += len(np.ravel(A1))

    
    print('\n \n')

print(count)

[-4. -3. -4. -3.]
[-2. -1. -2. -1.]
[0. 1. 0. 1.]
[2. 3. 2. 3.]

 

[-4. -3. -4. -3.]
[-2. -1. -2. -1.]
[0. 1. 0. 1.]
[2. 3. 2. 3.]

 

[-4. -3. -4. -3.]
[-2. -1. -2. -1.]
[0. 1. 0. 1.]
[2. 3. 2. 3.]

 

[-4. -3. -4. -3.]
[-2. -1. -2. -1.]
[0. 1. 0. 1.]
[2. 3. 2. 3.]

 

64


In [6]:
print(A.ravel())

[0. 2. 4. 6. 8. 0. 2. 4. 6. 8. 0. 2. 4. 6. 8. 0. 2. 4. 6. 8. 0. 2. 4. 6.
 8.]
