# Degeneracies (before checking literature and Zee)

In [ ]:
#providing a triplet of numbers should yield the degeneracy of the system

a,b,c  = 1,2,3

#generate permutations for triplet

#negate one of the entries



In [123]:
import numpy as np
from scipy.special import factorial
in_array = abs(np.array([1,2,3]))


vals, freq = np.unique(in_array, return_counts=True)

degeneracy = 0
ongoing = True
k = np.unique(in_array, return_counts=True)
modes = np.stack(k, axis  = 1) #first entry is number, second freq
modes_no_zero = modes[modes[:,0] != 0]


flip_rep = [modes[i,1]+1 for i in range(len(modes))  if modes[i,0] != 0 ]

flips = int(np.prod(flip_rep))

for i in range(flips):
    #here use the multibase representation to assign a number to a sign flip.

    key = np.array([])
    rest = i
    digit_value = flips
    for k in range(len(flip_rep),0,-1):
        digit_value //= flip_rep[k-1]
        key = np.append(key, rest//digit_value)
        rest = rest%digit_value
    key = key[::-1]

    new_array = np.array([])
    for j in range(len(key)):
        flipped = [modes_no_zero[j,0]*(-1)]
        non_flipped = [modes_no_zero[j,0]]
        new_array = np.append(new_array, flipped*int(key[j])  )
        new_array = np.append(new_array, non_flipped*int(modes_no_zero[j,1]-key[j])  )

    if len(new_array)<len(in_array):
        new_array = np.append(new_array, np.zeros(len(in_array)-len(new_array)))

    print(new_array)
    new_occurance = np.unique(new_array, return_counts=True)[1]
    degeneracy += factorial(len(new_array))/np.product(factorial(new_occurance))

print(degeneracy)



while ongoing:



    #2**()

    #1,2,3

    #(0,0,0) -> (1,0,0) -> (0,1,0) -> ... -> (1,1,1)

    #(2,2,0)

    #(0,0,0) -> (1,0,0)  = (0,1,0) -> (1,1,0)

    #(0,0)->(1,0)->(2,0)

    #overall flips: modes + 1 (excluding 0) and multiplied together

    #(3,3,3) --> (3,3) -> 4

    #(2,2,1) --> 6






    ongoing = False



[1. 2. 3. 3.]
[-1.  2.  3.  3.]
[ 1. -2.  3.  3.]
[-1. -2.  3.  3.]
[ 1.  2. -3.  3.]
[-1.  2. -3.  3.]
[ 1. -2. -3.  3.]
[-1. -2. -3.  3.]
[ 1.  2. -3. -3.]
[-1.  2. -3. -3.]
[ 1. -2. -3. -3.]
[-1. -2. -3. -3.]
192.0


In [43]:
list(np.array([45,2]))

[45, 2]

In [94]:

a = np.array([1,2,3])
print(factorial(a))

2/a

[1. 2. 6.]


array([2.        , 1.        , 0.66666667])

 1 2 0 1
 2 5 3 8

= 1 + 4 + 


2,3,2,3


1
01
11
02
12



10

021



