In [2]:
from standard_imports import *
import os
%load_ext autoreload
%autoreload 2


In [8]:
def derivative_location(d_vec, ML):
    d_vec = np.array(d_vec)
    directory = "derivatives/ML_{}/".format(ML)
    folder_name = "d_" + str(d_vec).replace(" ", "").replace("[", "").replace("]", "")
    file_name = "data"
    base_path = os.path.join(directory,folder_name, file_name)
    path_full = f"{base_path}_{{}}.npz"
    counter = 0
    while os.path.exists(path_full.format(counter)):
        counter += 1

    counter -= 1
    return path_full.format(counter)

In [15]:
d_vec = np.array([0,0,0])
ML = 4

In [16]:
zeros = np.load(file_location(d_vec, ML))['zeros'] 

In [18]:
print(np.round(zeros, 7))

[ 0.4728942  1.4415913  2.6270076  3.5366199  4.251706   5.5377008
  7.1962632  8.2879537  9.5345314 10.5505341 11.7014957 12.3102392
 13.3831152 15.3537375 16.1218253 17.5325415 18.6053932 19.5186394
 20.4033187 21.6944179]


In [ ]:
derivative(1,d_vec, )

In [ ]:


def get_der_at_root_automated(root_final=0.4728942473179055,
                              iterations=50):
    alpha = 0.5
    cut = 10
    value = derivative(1,root_final, cut, alpha)
    returned_value = value
    increasing_cut = True
    tolerence = 1e-10
    saved_values = []
    for i in range(iterations):
        if increasing_cut:
            cut += 1
            value_tmp = zeta_function_der(root_final, cut, alpha)
            if np.abs(value_tmp-value) < tolerence:
                increasing_cut = False
                saved_values.append([value_tmp, cut, alpha])
                returned_value = value_tmp
            value = value_tmp
        else:
            alpha = alpha/2.
            value_tmp = zeta_function_der(root_final, cut, alpha)
            if np.abs(value_tmp-value) > tolerence:
                increasing_cut = True
    saved_values = np.array(saved_values)
    return returned_value, saved_values

In [24]:
data = np.load("temp.npz")

print(data['Z'])

[[ 13.970069280514013  13.985438989806152  13.978324228566686  13.978322165078554  13.978322165078554  13.97832216507855   13.978322165078556  13.978322165078556  13.978322165078556  13.978322165078556]
 [ 14.160668077060489  14.1663175877453    14.001322393784479  13.98647318808934   13.986469906902045  13.98646990690206   13.986469906902048  13.986469906902048  13.986469906902048  13.986469906902048]
 [ 14.962755327794405  14.951716864306329  14.40775311388254   14.018162779540928  13.988742864590956  13.988737064463816  13.98873706446382   13.98873706446382   13.98873706446382   13.98873706446382 ]
 [ 16.913920651026555  16.895698293357135  16.106517868214024  14.828329847940529  14.045600496367685  13.989378709217826  13.989367914522811  13.989367914522811  13.989367914522811  13.989367914522811]
 [ 20.907524384060338  20.887048054169874  20.008817532092017  18.162595604164252  15.601677306642376  14.096422771719697  13.989563824116148  13.989543452299094  13.989543452299094  13.98

In [ ]:
plt.

In [22]:
np.set_printoptions(precision=15, linewidth=1000)

In [ ]:
11.214751530214611