In [2]:
from standard_imports import *
import os
%load_ext autoreload
%autoreload 2


In [8]:
def derivative_location(d_vec, ML):
    d_vec = np.array(d_vec)
    directory = "derivatives/ML_{}/".format(ML)
    folder_name = "d_" + str(d_vec).replace(" ", "").replace("[", "").replace("]", "")
    file_name = "data"
    base_path = os.path.join(directory,folder_name, file_name)
    path_full = f"{base_path}_{{}}.npz"
    counter = 0
    while os.path.exists(path_full.format(counter)):
        counter += 1

    counter -= 1
    return path_full.format(counter)

In [15]:
d_vec = np.array([0,0,0])
ML = 4

In [16]:
zeros = np.load(file_location(d_vec, ML))['zeros'] 

In [18]:
print(np.round(zeros, 7))

[ 0.4728942  1.4415913  2.6270076  3.5366199  4.251706   5.5377008
  7.1962632  8.2879537  9.5345314 10.5505341 11.7014957 12.3102392
 13.3831152 15.3537375 16.1218253 17.5325415 18.6053932 19.5186394
 20.4033187 21.6944179]


In [ ]:
derivative(1,d_vec, )

In [ ]:


def get_der_at_root_automated(root_final=0.4728942473179055,
                              iterations=50):
    alpha = 0.5
    cut = 10
    value = derivative(1,root_final, cut, alpha)
    returned_value = value
    increasing_cut = True
    tolerence = 1e-10
    saved_values = []
    for i in range(iterations):
        if increasing_cut:
            cut += 1
            value_tmp = zeta_function_der(root_final, cut, alpha)
            if np.abs(value_tmp-value) < tolerence:
                increasing_cut = False
                saved_values.append([value_tmp, cut, alpha])
                returned_value = value_tmp
            value = value_tmp
        else:
            alpha = alpha/2.
            value_tmp = zeta_function_der(root_final, cut, alpha)
            if np.abs(value_tmp-value) > tolerence:
                increasing_cut = True
    saved_values = np.array(saved_values)
    return returned_value, saved_values

In [6]:
import numpy as np


[[11.117246357231458 11.212910910003405 11.214751503263383 11.214751530214611 11.214751530214613 11.21475153021461  11.214751530214611 11.214751530214611 11.214751530214611 11.214751530214611]
 [10.847473575335464 11.159741824264481 11.213869104319437 11.214751516034907 11.214751530261765 11.214751530261768 11.214751530261765 11.214751530261765 11.214751530261765 11.214751530261765]
 [10.564658374133417 11.01396222866041  11.186951756011425 11.214285090741539 11.214751522823471 11.21475153027489  11.214751530274885 11.214751530274885 11.214751530274885 11.214751530274885]
 [10.364776685240074 10.86355959070835  11.111422191926543 11.200076322896152 11.214506097855491 11.21475152634806  11.214751530278535 11.214751530278535 11.214751530278535 11.214751530278535]
 [10.244197771178111 10.757827393145009 11.032723374635456 11.16023352994082  11.207019570852745 11.214622085844805 11.21475152820473  11.214751530279562 11.214751530279562 11.214751530279562]
 [10.176306843602527 10.69415630350

In [7]:
data = np.load("temp.npz")

print(data['Z'])

[[11.117246357231458 11.212910910003405 11.214751503263383 11.214751530214611 11.214751530214613 11.21475153021461  11.214751530214611 11.214751530214611 11.214751530214611 11.214751530214611]
 [10.847473575335464 11.159741824264481 11.213869104319437 11.214751516034907 11.214751530261765 11.214751530261768 11.214751530261765 11.214751530261765 11.214751530261765 11.214751530261765]
 [10.564658374133417 11.01396222866041  11.186951756011425 11.214285090741539 11.214751522823471 11.21475153027489  11.214751530274885 11.214751530274885 11.214751530274885 11.214751530274885]
 [10.364776685240074 10.86355959070835  11.111422191926543 11.200076322896152 11.214506097855491 11.21475152634806  11.214751530278535 11.214751530278535 11.214751530278535 11.214751530278535]
 [10.244197771178111 10.757827393145009 11.032723374635456 11.16023352994082  11.207019570852745 11.214622085844805 11.21475152820473  11.214751530279562 11.214751530279562 11.214751530279562]
 [10.176306843602527 10.69415630350

In [4]:
np.set_printoptions(precision=15, linewidth=1000)

In [12]:
dat = np.load("root_stability/ML_4/d_000/data.npz", allow_pickle=True)

In [14]:
for i in dat.files:
    print(i)

ALPHA_TOTAL
CUTOFF_TOTAL
Z_TOTAL
zeros_before
asymptotes_before
meta_data


In [16]:
dat['Z_TOTAL'][0]

array([[0.663327730115103, 0.523503116572294, 0.478718756155442, 0.473118135782014, 0.472895868070292, 0.472894248104115],
       [0.535356212536085, 0.480150928446542, 0.473172256703201, 0.472896245797602, 0.472894248289923, 0.47289424725966 ],
       [0.481965589775637, 0.473241345509121, 0.472896731072276, 0.472894248530616, 0.472894247259662, 0.472894247259652],
       [0.473331643962549, 0.472897379402876, 0.47289424886392 , 0.472894247259664, 0.472894247259651, 0.472894247259651],
       [0.472898194802333, 0.472894249282801, 0.472894247259667, 0.472894247259651, 0.472894247259652, 0.472894247259651],
       [0.472894249797585, 0.47289424725967 , 0.472894247259651, 0.472894247259651, 0.472894247259652, 0.472894247259651]])

In [ ]:
0.47289424745668485
0.472894247259651
0.472894248699386

In [18]:
dat2= np.load("roots_zeta/ML_4/d_000/data.npz", allow_pickle=True)
print(dat2['zeros'])

[ 0.472894248699386  1.441591313657851  2.62700761230748   3.536619947663408  4.251705973624203  5.537700774672     7.196263202615586  8.287953654425843  9.53453142742945  10.55053411627602  11.701495743249124 12.310239181089791 13.383115150471767 15.353737467186152 16.12182533121825  17.532541534431186 18.605393175988226 19.518639372215425 20.403318680414294 21.694417867168394]


In [20]:
from standard_imports import *

In [23]:

ML =4

np.load(file_location(np.array([0,0,0]), ML))